# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RepoViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RepoViewer
  pod 'Apollo'
  pod 'ApolloAlamofire'
  pod 'OAuthSwift'
  pod 'RxCocoa'
  pod 'RxSwift'

end
